apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-admin-frontend
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kube-admin.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: kube-admin-frontend
  template:
    metadata:
      labels:
        app: kube-admin-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: 80
