{{- if or .Values.secrets.jwtSecret .Values.secrets.encryptKey .Values.secrets.dbDSN }}
apiVersion: v1
kind: Secret
metadata:
  name: kube-admin-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kube-admin.labels" . | indent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  encrypt-key: {{ .Values.secrets.encryptKey | quote }}
  db-dsn: {{ .Values.secrets.dbDSN | quote }}
{{- end }}
